# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    commit-message:
      prefix: "deps"
      include: "scope"
