---
# Label rules for GitHub labeler

codex:
  - base-branch: 'codex/**'

documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
      - any-glob-to-any-file: 'docs/**/*'

tests:
  - changed-files:
      - any-glob-to-any-file: 'tests/**/*'

core:
  - changed-files:
      - any-glob-to-any-file: 'core/**/*'
  - changed-files:
      - any-glob-to-any-file: 'connect/**/*'

docs:
  - changed-files:
      - any-glob-to-any-file: 'README.md'
  - changed-files:
      - any-glob-to-any-file: 'CONTRIBUTING.md'

enhancement:
  - added-files:
      - any-glob-to-any-file: 'core/**/*'
      - any-glob-to-any-file: 'connect/**/*'
