---
tests:
  - changed-files:
      - any-glob-to-any-file: 'tests/**/*'
core:
  - changed-files:
      - any-glob-to-any-file: 'core/**/*'
docs:
  - changed-files:
      - any-glob-to-any-file: 'README.md'
  - changed-files:
      - any-glob-to-any-file: 'CONTRIBUTING.md'

