codex:
  - base-branch: 'codex/**'

documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
      - any-glob-to-any-file: 'docs/**/*'

enhancement:
  - added-files:
      - any-glob-to-any-file: 'core/**/*'
      - any-glob-to-any-file: 'connect/**/*'