---
# Label rules for GitHub labeler

documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
      - any-glob-to-any-file: 'docs/**/*'

tests:
  - changed-files:
      - any-glob-to-any-file: 'tests/**/*'

core:
  - changed-files:
      - any-glob-to-any-file: 'core/**/*'
  - changed-files:
      - any-glob-to-any-file: 'connect/**/*'

docs:
  - changed-files:
      - any-glob-to-any-file: 'README.md'
  - changed-files:
      - any-glob-to-any-file: 'CONTRIBUTING.md'

enhancement:
  - changed-files:
      - any-glob-to-any-file: 'core/**/*'
      - any-glob-to-any-file: 'connect/**/*'
