name: "CI Build"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Sync dependencies
        run: pip-sync requirements/requirements.txt

      - name: Check pip-compile freshness
        run: |
          pip-compile requirements/requirements.in --quiet
          git diff --exit-code requirements/requirements.txt

      - name: Install test dependencies
        run: pip install pytest pytest-cov

      - name: Run tests with coverage
        run: pytest --cov=core --cov-report=xml --disable-warnings --maxfail=1

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml