name: CLI Check

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  cli:
    runs-on: ubuntu-22.04

    env:
      BASIC_AUTH: ${{ secrets.BASIC_AUTH }}
      NOM_KEY: ${{ secrets.NOM_KEY }}
      N2YO_KEY: ${{ secrets.N2YO_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          pip install pip-tools
          pip-sync requirements/requirements.txt
          pip install pytest

      - name: Run CLI test
        run: python core/import_udl_to_nominal.py --help || true