name: "pip-compile"

on:
  push:
    paths:
      - 'requirements/*.in'
  pull_request:
    paths:
      - 'requirements/*.in'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  compile:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Compile requirements
        run: pip-compile requirements/requirements.in

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add requirements/requirements.txt
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update requirements.txt" && git push
          fi
