name: Python CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]  # Triggers on version tags like v0.1.0
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install pip-tools
      run: pip install pip-tools

    - name: Sync dependencies
      run: pip-sync requirements/requirements.txt

    - name: Install flake8
      run: pip install flake8

    - name: Run flake8
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Install test dependencies
      run: pip install pytest

    - name: Run unit tests
      run: pytest --disable-warnings --maxfail=1
    
    - name: Run basic CLI check
      run: python core/import_udl_to_nominal.py --help || true