name: Python CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]  # Triggers on version tags like v0.1.0
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install pip-tools
      run: pip install pip-tools

    - name: Sync dependencies
      run: pip-sync requirements.txt

    - name: Run script
      run: python import_udl_to_nominal.py

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}