name: test

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Sync dependencies
        run: pip-sync requirements/requirements.txt

      - name: Install test dependencies
        run: pip install pytest

      - name: Run unit tests
        run: pytest --disable-warnings --maxfail=1